version: '3.4'

services:
  dockercomposedebug.webapi1:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - "80"

  dockercomposedebug.webapi2:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - "80"
