version: '3.4'

services:
  dockercomposedebug.webapi1:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS=https://+443;http://+:80 
      - ASPNETCORE_HTTP_PORTS=80
#      - ASPNETCORE_HTTPS_PORTS=443
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx- 
    ports:
      - "8080:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  dockercomposedebug.webapi2:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS=https://+443;http://+:80 
      - ASPNETCORE_HTTP_PORTS=80
#      - ASPNETCORE_HTTPS_PORTS=443
    ports:
      - "9090:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  # nginx:
  #   ports:
  #     - "8080:8080"
  #     - "9090:9090"
  #   networks:
  #     - DockerComposeDebug
