#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/DockerComposeDebug.WebApi1/DockerComposeDebug.WebApi1.csproj", "src/DockerComposeDebug.WebApi1/"]
RUN dotnet restore "./src/DockerComposeDebug.WebApi1/./DockerComposeDebug.WebApi1.csproj"
COPY . .
WORKDIR "/src/src/DockerComposeDebug.WebApi1"
RUN dotnet build "./DockerComposeDebug.WebApi1.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./DockerComposeDebug.WebApi1.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DockerComposeDebug.WebApi1.dll"]